version: "3.9"

services:
    db:
        container_name: ya2ber-db
        image: postgres:17.2
        restart: unless-stopped
        environment:
            - POSTGRES_DB=${DATABASE_NAME}
            - POSTGRES_USER=${DATABASE_USER}
            - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
        ports:
            - "5432:5432"
        volumes:
            - ./src/database/init.sql:/docker-entrypoint-initdb.d/init.sql

    server:
        container_name: ya2ber-server
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            - PORT=${PORT}
        restart: unless-stopped
        depends_on:
            - db
        ports:
            - "8080:8080"
